In [1]:
import numpy as np
np.random.seed(10)

In [2]:
from keras.utils import np_utils

In [3]:
from keras.datasets import mnist

In [4]:
(x_train_image, y_train_label), (x_test_image, y_test_label) = mnist.load_data()

11490434/11490434 [==============================] - 5s 0us/step


In [5]:
print('shape of train image=', x_train_image.shape)
print('shape of test image=', x_test_image.shape)

shape of train image= (60000, 28, 28)
shape of test image= (10000, 28, 28)


In [6]:
reshape_dim = 28 * 28
x_train_reshaped = x_train_image.reshape(60000, reshape_dim).astype('float32')
x_test_reshaped = x_test_image.reshape(10000, reshape_dim).astype('float32')

In [7]:
x_train_normalized = x_train_reshaped / 255
x_test_normalized = x_test_reshaped / 255

In [8]:
print(y_train_label[:5])
print(y_test_label[:5])

[5 0 4 1 9]
[7 2 1 0 4]


In [9]:
y_train_oneHotEncoding = np_utils.to_categorical(y_train_label)
y_test_oneHotEncoding = np_utils.to_categorical(y_test_label)

In [10]:
print(y_train_oneHotEncoding[:5])
print(y_test_oneHotEncoding[:5])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [11]:
print(x_train_normalized.shape)
print(y_train_oneHotEncoding.shape)

(60000, 784)
(60000, 10)


In [24]:
from keras.models import Sequential
from keras.layers import Dense
from keras.utils.vis_utils import plot_model

In [13]:
from keras.layers import Dropout

In [14]:
model = Sequential()

In [15]:
model.add( Dense(units=512, input_dim=784, kernel_initializer='normal', activation='relu') )
model.add( Dropout(0.5))

In [16]:
model.add( Dense(units=128, input_dim=784, kernel_initializer='normal', activation='relu') )
model.add( Dropout(0.5))

In [17]:
model.add( Dense(units=10, kernel_initializer='normal', activation='softmax') )

In [18]:
print( model.summary() )

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dropout (Dropout)           (None, 512)               0         
                                                                 
 dense_1 (Dense)             (None, 128)               65664     
                                                                 
 dropout_1 (Dropout)         (None, 128)               0         
                                                                 
 dense_2 (Dense)             (None, 10)                1290      
                                                                 
Total params: 468,874
Trainable params: 468,874
Non-trainable params: 0
_________________________________________________________________
None


In [19]:
model.compile( loss='categorical_crossentropy', optimizer= 'adam', metrics=['accuracy'])

In [20]:
train_history = model.fit( x=x_train_normalized, y=y_train_oneHotEncoding, validation_split=0.2, epochs=10, batch_size=50, verbose=2)
# note: verbose=2 means to show the training process

Epoch 1/10
960/960 - 7s - loss: 0.4281 - accuracy: 0.8703 - val_loss: 0.1478 - val_accuracy: 0.9563 - 7s/epoch - 8ms/step
Epoch 2/10
960/960 - 6s - loss: 0.1958 - accuracy: 0.9410 - val_loss: 0.1115 - val_accuracy: 0.9661 - 6s/epoch - 6ms/step
Epoch 3/10
960/960 - 7s - loss: 0.1567 - accuracy: 0.9544 - val_loss: 0.1017 - val_accuracy: 0.9693 - 7s/epoch - 7ms/step
Epoch 4/10
960/960 - 7s - loss: 0.1316 - accuracy: 0.9603 - val_loss: 0.1007 - val_accuracy: 0.9709 - 7s/epoch - 7ms/step
Epoch 5/10
960/960 - 8s - loss: 0.1173 - accuracy: 0.9642 - val_loss: 0.0920 - val_accuracy: 0.9736 - 8s/epoch - 8ms/step
Epoch 6/10
960/960 - 7s - loss: 0.1080 - accuracy: 0.9683 - val_loss: 0.0875 - val_accuracy: 0.9768 - 7s/epoch - 7ms/step
Epoch 7/10
960/960 - 7s - loss: 0.1006 - accuracy: 0.9700 - val_loss: 0.0827 - val_accuracy: 0.9759 - 7s/epoch - 7ms/step
Epoch 8/10
960/960 - 7s - loss: 0.0920 - accuracy: 0.9726 - val_loss: 0.0794 - val_accuracy: 0.9774 - 7s/epoch - 7ms/step
Epoch 9/10
960/960 - 7s 

In [21]:
import matplotlib.pyplot as pyplot
def my_show_train_history(input_train_history, input_train, input_validation):
    pyplot.plot(input_train_history.history[input_train] )
    pyplot.plot(input_train_history.history[input_validation])
    pyplot.title('Train History')
    pyplot.ylabel(input_train)
    # pyplot.ylabel('Accuracy')
    pyplot.xlabel('Epoch')
    pyplot.legend(['my_train','my_validation'], loc='upper left')
    pyplot.show()

In [25]:
plot_model(model, to_file='model.png', show_shapes=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [22]:
my_show_train_history(train_history, 'acc', 'val_acc')

KeyError: 'acc'

In [ ]:
my_show_train_history(train_history, 'loss', 'val_loss')

In [ ]:
# after training (and validation), then using public test_data for evaluation 
scores = model.evaluate(x_test_normalized, y_test_oneHotEncoding)
print(scores)
print('accuracy=', scores[1])

In [ ]:
prediction = model.predict_classes(x_test_normalized)

In [ ]:
prediction

In [ ]:
import matplotlib.pyplot as pyplot
def my_plot_images_labels_prediction(input_images, input_labels, input_prediction, input_index, input_num=10):
    fig = pyplot.gcf()
    fig.set_size_inches(12,14)
    if input_num>10:
        input_num=10
    for i in range(0, input_num):
        ax = pyplot.subplot(5,5,1+i)
        ax.imshow(input_images[input_index], cmap='binary')
        title = "label=" + str(input_labels[input_index])
        if len(input_prediction)>0:
            title= title + ", predict=" + str(input_prediction[input_index])
        ax.set_title(title,fontsize=10)
        ax.set_xticks([])
        ax.set_yticks([])
        input_index = input_index + 1
    pyplot.show()

In [ ]:
my_plot_images_labels_prediction(x_test_image, y_test_label, prediction, input_index=1393, input_num=5)

In [ ]:
# confusion matrix
import pandas as pd
pd.crosstab(y_test_label, prediction, rownames=['label'],colnames=['predict'])

In [ ]:
df = pd.DataFrame({'label':y_test_label, 'predict':prediction})
df

In [ ]:
df[:2]

In [ ]:
# find "label=5, but predict=3"
df[(df.label==5)&(df.predict==3)]

In [ ]:
my_plot_images_labels_prediction(x_test_image, y_test_label, prediction, input_index=1393, input_num=1)